server:
  port: 8080

spring:
  application:
    name: llm-agent-system
  profiles:
    active: dev

llm-service:
  provider: simulation  # Change to anthropic, openai, etc. when ready
  api-key: ${LLM_API_KEY:your-api-key-here}
  model: simulation  # Change to claude-3-haiku-20240307, gpt-4, etc. when ready
  max-tokens: 1024
  temperature: 0.7

